#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1
#PROCD_DEBUG=1

start_service()
{
	procd_open_instance
    procd_set_param respawn ${respawn_timeout:-31} ${respawn_retry:-5}
	procd_set_param command "/bin/sh" /root/wan_watcher.sh
    procd_set_param user root # run service as user root
	procd_close_instance
#   logger -t "WAN_Watcher" "wan_watcher.sh started."
}


